version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: wedding-frontend-dev
    volumes:
      - ./:/app   # map source code để live reload
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
